name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 .

      - name: Run tests + coverage (XML artifact)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p artifacts
          pytest --cov=app --cov-report=term --cov-report=xml:artifacts/coverage.xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: artifacts/coverage.xml
